### ISSUE TITLE
DDPAI rtsp/tcp streaming link

### ISSUE THREAD

**Issue by littlecorsican** [Awexander/ddpai-api#2]
hi good work there!

Just want to ask have you manage to figure out what is the rtsp or tcp streaming link that ddpai uses?

i have looked through your api.py i dont believe i have seen it. would be nice if we can see the live preview using vlc player

Regards

**Comment by awexandrr** [comment]
Hi, live preview of camera can be found on this endpoint: 
front camera : rtsp://193.168.0.1:554/liveRTSP/av4
rear camera : rtsp://193.168.0.1:554/liveRTSP/av5
